import React, { useState, useEffect } from 'react';
import { X, Sparkles, Copy, Check, Send, Mail, Loader2 } from 'lucide-react';
import { CandidateApplication } from '../../types';
import { aiApi } from '../../lib/api';

interface AIFollowUpModalProps {
  application: CandidateApplication;
  onClose: () => void;
}

export const AIFollowUpModal: React.FC<AIFollowUpModalProps> = ({ application, onClose }) => {
  const [templateType, setTemplateType] = useState<'interview' | 'feedback' | 'offer'>('interview');
  const [copied, setCopied] = useState(false);
  const [sent, setSent] = useState(false);
  const [loading, setLoading] = useState(false);
  const [emailSubject, setEmailSubject] = useState('');
  const [emailBody, setEmailBody] = useState('');
  const [error, setError] = useState('');

  const generateEmail = async (type: 'interview' | 'feedback' | 'offer') => {
    setLoading(true);
    setError('');
    try {
      const res = await aiApi.generateEmail(
        type,
        application.candidateName || '',
        application.jobTitle,
        application.company,
        `Match score: ${application.matchScore}%`
      );
      setEmailSubject(res.data.subject);
      setEmailBody(res.data.body);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : 'Failed to generate email';
      setError(msg);
      setEmailSubject(`Follow-up: ${application.jobTitle}`);
      setEmailBody(`Hi ${application.candidateName || 'Candidate'},\n\nThank you for your interest in the ${application.jobTitle} position at ${application.company}. We will be in touch soon.\n\nBest regards,\n${application.company} Recruitment Team`);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    generateEmail(templateType);
  }, [templateType]);

  const handleCopy = () => {
    navigator.clipboard.writeText(`Subject: ${emailSubject}\n\n${emailBody}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSend = () => {
    setSent(true);
    setTimeout(() => onClose(), 1500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="w-full max-w-xl bg-[#18181B] border border-[#27272A] rounded-2xl shadow-2xl overflow-hidden glass-card">
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#27272A] bg-[#111827]">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-purple-500/10 text-purple-400 border border-purple-500/30">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white">AI Follow-Up Assistant</h2>
              <p className="text-xs text-gray-400">Candidate: {application.candidateName} ({application.jobTitle})</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1.5 text-gray-400 hover:text-white rounded-lg hover:bg-white/5">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 space-y-4">
          <div className="flex gap-2 p-1 bg-[#111827] border border-[#27272A] rounded-xl">
            {(['interview', 'feedback', 'offer'] as const).map((type) => (
              <button
                key={type}
                onClick={() => setTemplateType(type)}
                className={`flex-1 py-1.5 text-xs font-semibold rounded-lg capitalize transition-all ${
                  templateType === type
                    ? 'bg-purple-600 text-white shadow-md'
                    : 'text-gray-400 hover:text-white'
                }`}
              >
                {type === 'interview' ? 'Interview Invite' : type === 'feedback' ? 'Status Update' : 'Extend Offer'}
              </button>
            ))}
          </div>

          {error && (
            <div className="text-xs text-amber-400 bg-amber-500/10 border border-amber-500/20 rounded-lg px-3 py-2">
              {error}
            </div>
          )}

          <div className="p-4 bg-[#09090B] border border-[#27272A] rounded-xl font-mono text-xs text-gray-200 space-y-2 relative group min-h-[200px]">
            <div className="flex items-center justify-between border-b border-[#27272A] pb-2 text-gray-400 text-[11px]">
              <span>To: {application.candidateEmail || 'candidate@example.com'}</span>
              <span className="text-purple-400 flex items-center gap-1">
                {loading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Sparkles className="w-3 h-3" />}
                {loading ? 'Generating...' : 'Generated by Groq AI'}
              </span>
            </div>
            {loading ? (
              <div className="flex items-center justify-center py-8">
                <Loader2 className="w-6 h-6 text-purple-400 animate-spin" />
              </div>
            ) : (
              <div>
                <div className="text-gray-400 mb-1">Subject: <span className="text-white">{emailSubject}</span></div>
                <textarea
                  readOnly
                  rows={8}
                  value={emailBody}
                  onChange={(e) => setEmailBody(e.target.value)}
                  className="w-full bg-transparent resize-none text-gray-300 focus:outline-none leading-relaxed"
                />
              </div>
            )}
          </div>
        </div>

        <div className="px-6 py-4 border-t border-[#27272A] bg-[#111827] flex items-center justify-between">
          <button
            onClick={handleCopy}
            disabled={loading}
            className="flex items-center gap-1.5 px-4 py-2 bg-[#18181B] border border-[#27272A] text-gray-300 rounded-xl text-xs font-semibold hover:border-gray-500 disabled:opacity-50"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied to Clipboard' : 'Copy Email Text'}
          </button>

          <button
            onClick={handleSend}
            disabled={sent || loading}
            className="flex items-center gap-2 px-6 py-2 bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-500 hover:to-blue-500 text-white rounded-xl text-xs font-bold shadow-lg shadow-purple-600/20 disabled:opacity-50"
          >
            {sent ? (
              <>
                <Check className="w-4 h-4 text-emerald-400" /> Sent via TalentIQ Relay!
              </>
            ) : (
              <>
                <Send className="w-4 h-4" /> Send Follow-up Email
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
